steps:
- id: "Compilando"
  name : 'gcr.io/cloud-builders/go'
  args: ['build', 'calcular.go']
  dir: 'src'
  env: ["GOPATH=."]

- id: "rodando testes unitarios"
  name: 'gcr.io/cloud-builders/go'
  args: ['test']
  dir: 'src'
  env: ["GOPATH=."]

- id: "Building image from Dockerfile"
  name: "gcr.io/cloud-builders/docker"
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/app-go:$SHORT_SHA', '-f', 'Dockerfile', '.']

- id: "Pushing image"
  name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/app-go:$SHORT_SHA']

- id: "Adjusting deployment file no k8s"
  name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: '/bin/sh'
  args: 
    - '-c'
    - |
      sed 's#img-app-deployment#gcr.io/$PROJECT_ID/app-go:$SHORT_SHA#g' kubernetes/deployment.yaml > kubernetes/deployment-new.yaml;
      cat kubernetes/deployment-new.yaml;

- id: "Deploying k8s"
  name: 'gcr.io/cloud-builders/kubectl'
  args:
    - 'apply'
    - '-f'
    - 'kubernetes/deployment-new.yaml'
  env:
    - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
    - 'CLOUDSDK_CONTAINER_CLUSTER=cluster-docker-laravel'