steps:
- id: "Compilando"
  name : 'gcr.io/cloud-builders/go'
  args: ['build', 'calcular.go']
  dir: 'go/src'
  env: ["GOPATH=."]

- id: "rodando testes unitarios"
  name: 'gcr.io/cloud-builders/go'
  args: ['test']
  dir: 'go/src'
  env: ["GOPATH=."]